general.live_config_reload = true

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true


# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d2021'
cursor = '0xd5c4a1'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[[colors.indexed_colors]]
index = 16
color = "0xfe8019"

[[colors.indexed_colors]]
index = 17
color = "0xd65d0e"

[[colors.indexed_colors]]
index = 18
color = "0x3c3836"

[[colors.indexed_colors]]
index = 19
color = "0x504945"

[[colors.indexed_colors]]
index = 20
color = "0xbdae93"

[[colors.indexed_colors]]
index = 21
color = "0xebdbb2"

[cursor]
unfocused_hollow = true
style = { blinking = "Always" }
vi_mode_style = { blinking = "Always" }
blink_interval = 350
blink_timeout = 0

[font]
size = 9.0

[font.normal]
family = "Iosevka Custom"
style = "Medium"

[font.italic]
family = "Iosevka Custom"
style = "Italic"

[font.bold]
family = "Iosevka Custom"
style = "Bold"

[font.bold_italic]
family = "Iosevka Custom"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
key = "Semicolon"
mods = "Control"
chars = "\u001b[2~"

[mouse]
hide_when_typing = true

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "/usr/bin/fish"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 1

[window.padding]
x = 5
y = 0
